ALTER TABLE "Link" ADD COLUMN "redirectType" TEXT NOT NULL DEFAULT '302';
ALTER TABLE "Link" ADD COLUMN "ogTitle" TEXT;
ALTER TABLE "Link" ADD COLUMN "ogDescription" TEXT;
ALTER TABLE "Link" ADD COLUMN "ogImage" TEXT;
